CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE,
  password TEXT,

  win1 INTEGER DEFAULT 0,
  win2 INTEGER DEFAULT 0,
  win3 INTEGER DEFAULT 0,
  win4 INTEGER DEFAULT 0,

  rating INTEGER DEFAULT 1500,
  dan INTEGER DEFAULT 1,
  comment TEXT DEFAULT ""
);
